theme: jekyll-theme-hacker
title: GitHub @ Trimble
description: "The home of onboarding and contribution guidelines for Trimble GitHub users of all stripes: open source, inner source and projects for specific internal teams."
